'use strict';

/**
 * Pre-configured Europe 1 RSS feeds
 * Source: flux_europe1.xlsx
 */

const PODCASTS_E1 = [
  { id: 'e1-1',  name: 'Europe 1 Bonjour',                               url: 'https://feeds.audiomeans.fr/feed/17652c76-f6e2-47da-b4de-ab791a8de6f9.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-2',  name: 'Europe 1 Matin',                                  url: 'https://feeds.audiomeans.fr/feed/b38cbcd5-a1b8-4f4c-997a-d40c2c04f9e8.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-3',  name: "L'Heure des Pros",                                url: 'https://feeds.audiomeans.fr/feed/abd60e2a-fac4-413f-bf0a-463aa19796dc.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-4',  name: 'Culture Médias',                                  url: 'https://feeds.audiomeans.fr/feed/7b065cde-def6-4740-b96f-571366b7e54c.xml', category: 'Médias',      statut: 'comptabilisé' },
  { id: 'e1-5',  name: 'Christine Kelly et Vous',                         url: 'https://feeds.audiomeans.fr/feed/7b5cfe03-5ba9-4428-a41a-cf5c90d4ef49.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-6',  name: 'Europe 1 Info',                                   url: 'https://feeds.audiomeans.fr/feed/c0afb1da-71a8-4a43-8b2f-9decd86c3198.xml', category: 'Info',        statut: 'comptabilisé' },
  { id: 'e1-7',  name: "Les Enfants d'Europe 1",                          url: 'https://feeds.audiomeans.fr/feed/a8aae616-7e41-429f-a0f5-5b8d1c322fc7.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-8',  name: "Et si on en Parlait",                             url: 'https://feeds.audiomeans.fr/feed/ea13af31-37bf-4ed1-a0fb-87498c26d64b.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-9',  name: 'Pascal Praud et Vous',                            url: 'https://feeds.audiomeans.fr/feed/9562ff43-55ee-44af-95e0-db69d162ebae.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-10', name: 'Punchline',                                       url: 'https://feeds.audiomeans.fr/feed/4be07d58-3177-4e44-8c9a-9ab1eedd2c34.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-11', name: 'Europe 1 Soir',                                   url: 'https://feeds.audiomeans.fr/feed/aae35f24-4d4f-4976-bae5-0f629c3d08f5.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-12', name: 'La France Bouge',                                 url: 'https://feeds.audiomeans.fr/feed/b3d92b2e-f448-42fd-91ff-13e605c39ccd.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-13', name: 'Europe 1 Nuit',                                   url: 'https://feeds.audiomeans.fr/feed/23446ca3-fe7a-4be3-8dca-6f8a64a06806.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-14', name: 'La Libre Antenne',                                url: 'https://feeds.audiomeans.fr/feed/0f9366c9-ea8d-43d8-a7a0-135ca0c05a1d.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-15', name: 'Le Journal',                                      url: 'https://feeds.audiomeans.fr/feed/d46afe4c-2f13-4f73-9a6e-b36b2e37dcbf.xml', category: 'Info',        statut: 'hors-comptage' },
  { id: 'e1-16', name: "L'Interview Actu",                                url: 'https://feeds.audiomeans.fr/feed/4a8dccbe-3444-4c27-8f42-c26d21406bc1.xml', category: 'Interviews',  statut: 'comptabilisé' },
  { id: 'e1-17', name: 'Édito Éco',                                       url: 'https://feeds.audiomeans.fr/feed/0f56e4cd-d44d-4968-ac12-9d1159a54d4c.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-18', name: 'L\'Édito de Laurent Tessier',                     url: 'https://feeds.audiomeans.fr/feed/78a1e8b4-d078-44de-b74b-78f38a8923ae.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-19', name: 'L\'Édito International',                          url: 'https://feeds.audiomeans.fr/feed/6b9f30c8-cdf9-4ede-aada-aec380317df1.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-20', name: 'L\'Enquête de la Rédaction',                      url: 'https://feeds.audiomeans.fr/feed/49687653-10e2-4068-b513-a29218042228.xml', category: 'Info',        statut: 'comptabilisé' },
  { id: 'e1-21', name: 'La Revue de Presse',                              url: 'https://feeds.audiomeans.fr/feed/4483fcfa-6adc-47bc-97b8-c4c78ea4951e.xml', category: 'Info',        statut: 'comptabilisé' },
  { id: 'e1-22', name: 'L\'Édito Politique',                              url: 'https://feeds.audiomeans.fr/feed/456411ca-cea1-4a88-a9d5-98b990722ed6.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-23', name: 'La Grande Interview',                             url: 'https://feeds.audiomeans.fr/feed/9a5e8977-e246-4457-b438-51a1f498d911.xml', category: 'Interviews',  statut: 'comptabilisé' },
  { id: 'e1-24', name: 'Voyage en Absurdie',                              url: 'https://feeds.audiomeans.fr/feed/55f098ba-f624-42b7-b29b-e61099ce2b79.xml', category: 'Divertissement', statut: 'comptabilisé' },
  { id: 'e1-25', name: 'Prescriptions Culture',                           url: 'https://feeds.audiomeans.fr/feed/c50fd628-34ad-4eca-9def-546cb7c2ae31.xml', category: 'Culture',     statut: 'comptabilisé' },
  { id: 'e1-26', name: 'Europe 1 Matin Week-End',                        url: 'https://feeds.audiomeans.fr/feed/e7d6f6f9-6084-49e6-80ee-82e921b40d5d.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-27', name: "C'est Arrivé Cette Semaine",                      url: 'https://feeds.audiomeans.fr/feed/0ee58dde-db1f-4508-95c4-8e23bcc1ec9b.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-28', name: 'Face à Philippe de Villiers',                     url: 'https://feeds.audiomeans.fr/feed/84b3b99d-eb46-413b-9d96-595af98a3f79.xml', category: 'Interviews',  statut: 'comptabilisé' },
  { id: 'e1-29', name: 'Eliot Deval et Vous',                             url: 'https://feeds.audiomeans.fr/feed/134be58f-3f43-447f-baf9-3acc9262dcfd.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-30', name: 'Face à Michel Onfray',                            url: 'https://feeds.audiomeans.fr/feed/3f623a0b-f338-4e18-ba74-c194e0e6e8bf.xml', category: 'Interviews',  statut: 'comptabilisé' },
  { id: 'e1-31', name: 'Coeurs et Ames',                                  url: 'https://feeds.audiomeans.fr/feed/33dfee79-12e7-41c6-9023-7ac20bf91db1.xml', category: 'Divertissement', statut: 'comptabilisé' },
  { id: 'e1-32', name: "Les Histoires d'Amour Extraordinaires",           url: 'https://feeds.audiomeans.fr/feed/5799f0c0-d531-402b-8c09-14671fcccfb7.xml', category: 'Divertissement', statut: 'comptabilisé' },
  { id: 'e1-33', name: 'Balades en France',                               url: 'https://feeds.audiomeans.fr/feed/5d025ae3-c104-4b3c-b20d-0c5bdb4df97d.xml', category: 'Culture',     statut: 'comptabilisé' },
  { id: 'e1-34', name: 'Clap !',                                          url: 'https://feeds.audiomeans.fr/feed/1ef17db5-ad83-4c9f-84b7-449df8b38b32.xml', category: 'Culture',     statut: 'comptabilisé' },
  { id: 'e1-35', name: 'Europe 1 Soir Week-End',                         url: 'https://feeds.audiomeans.fr/feed/fc535eee-8df2-4f13-9d12-0d4c8c0d1154.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-36', name: 'Europe 1 Nuit Week-End',                         url: 'https://feeds.audiomeans.fr/feed/1019002c-dd56-48c1-808d-f1d0f5ec1113.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-37', name: 'La Libre Antenne Week-End',                      url: 'https://feeds.audiomeans.fr/feed/22ed053d-cd0c-4598-babe-8da182bfd557.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-38', name: 'Le Studio des Légendes',                         url: 'https://feeds.audiomeans.fr/feed/44b11857-392e-491a-ab69-69bd3543ec63.xml', category: 'Culture',     statut: 'comptabilisé' },
  { id: 'e1-39', name: 'Punchline Week-End (Thierry Cabannes)',           url: 'https://feeds.audiomeans.fr/feed/4be07d58-3177-4e44-8c9a-9ab1eedd2c34.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-40', name: "C'est Arrivé Demain",                             url: 'https://feeds.audiomeans.fr/feed/078c3a40-6a61-47ab-bf75-5653f3a1463f.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-41', name: 'Le Grand Rendez-Vous',                            url: 'https://feeds.audiomeans.fr/feed/ac193b03-3b95-435b-8c37-a01d5eda5d1d.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-42', name: "En Quête d'Esprit",                               url: 'https://feeds.audiomeans.fr/feed/dbada355-20e2-42ad-8901-6945bd8d4800.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-43', name: 'Le Poulet du Dimanche',                           url: 'https://feeds.audiomeans.fr/feed/2223a715-ca4a-4360-abe2-dc5a906c7fbb.xml', category: 'Divertissement', statut: 'comptabilisé' },
  { id: 'e1-44', name: 'Dis-moi ce que tu Chantes',                      url: 'https://feeds.audiomeans.fr/feed/a1cd7837-0832-4070-8e43-14d5beac123a.xml', category: 'Musique',     statut: 'comptabilisé' },
  { id: 'e1-45', name: 'La Voix est Livre',                               url: 'https://feeds.audiomeans.fr/feed/8f8a3fe9-5298-409e-b938-b1f990c2c8ad.xml', category: 'Culture',     statut: 'comptabilisé' },
  { id: 'e1-46', name: 'Hondelatte Raconte',                              url: 'https://feeds.audiomeans.fr/feed/1c147c6c-b4f0-46ae-a101-d0436ffa3d0e.xml', category: 'Divertissement', statut: 'comptabilisé' },
  { id: 'e1-47', name: "Au cœur de l'histoire",                           url: 'https://feeds.audiomeans.fr/feed/80a39a48-f044-436e-ad5b-63d3154efa91.xml', category: 'Histoire',    statut: 'comptabilisé' },
  { id: 'e1-48', name: 'Destins extraordinaires',                         url: 'https://feeds.audiomeans.fr/feed/13c59b4e-7b42-49a8-849f-d4eb25baeb19.xml', category: 'Histoire',    statut: 'comptabilisé' },
  { id: 'e1-49', name: 'Au cœur de la France',                            url: 'https://feeds.audiomeans.fr/feed/5a3426bf-0329-4df2-a63e-87169b371be7.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-50', name: 'Au cœur du crime',                                url: 'https://feeds.audiomeans.fr/feed/0b81db9c-9ba5-4faa-921c-3ae8ab7d15e2.xml', category: 'Faits divers', statut: 'comptabilisé' },
  { id: 'e1-51', name: 'Les histoires extraordinaires de Pierre Bellemare', url: 'https://feeds.audiomeans.fr/feed/13847b2e-82d3-11ee-af22-df4d4a91bfdc.xml', category: 'Histoire', statut: 'comptabilisé' },
  { id: 'e1-52', name: 'Les assassins sont parmi nous',                   url: 'https://feeds.audiomeans.fr/feed/a9132511-29db-4d76-bbf5-ad6e53a6375d.xml', category: 'Faits divers', statut: 'comptabilisé' },
  { id: 'e1-53', name: "Les dossiers d'Interpol",                         url: 'https://feeds.audiomeans.fr/feed/19e73a34-5dd4-4680-913f-a34294ccd927.xml', category: 'Faits divers', statut: 'comptabilisé' },
  { id: 'e1-54', name: 'Au cœur des archives',                            url: 'https://feeds.audiomeans.fr/feed/5ced65f3-0264-4fac-8785-d12d13b5c2f1.xml', category: 'Histoire',    statut: 'comptabilisé' },
  { id: 'e1-55', name: 'Signe Furax',                                     url: 'https://feeds.audiomeans.fr/feed/1075b04c-0b6b-4ba0-b129-e83c241aa304.xml', category: 'Divertissement', statut: 'comptabilisé' },
  { id: 'e1-56', name: 'Ivanhoe',                                         url: 'https://feeds.audiomeans.fr/feed/ee883851-2ab1-4296-b3f2-6f70f3a8f0e8.xml', category: 'Divertissement', statut: 'comptabilisé' },
  { id: 'e1-57', name: "Au cœur de l'actu",                               url: 'https://feeds.audiomeans.fr/feed/6f8c5a53-9a85-4f33-80ea-699424d45309.xml', category: 'Info',        statut: 'comptabilisé' },
  { id: 'e1-58', name: 'Bastie',                                          url: 'https://feeds.audiomeans.fr/feed/f649a24a-afec-4c3b-b01d-985223ff1e74.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-59', name: "D'Ornellas",                                      url: 'https://feeds.audiomeans.fr/feed/5938c170-dc0b-41a5-a59d-019a05f687c2.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-60', name: 'Catherine Nay',                                   url: 'https://feeds.audiomeans.fr/feed/1aceff0b-992d-4337-9f75-3dff622fd8af.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-61', name: 'Val',                                             url: 'https://feeds.audiomeans.fr/feed/76c7cbeb-73a8-41c6-9700-01818b258f27.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-62', name: 'La note secrète',                                 url: 'https://feeds.audiomeans.fr/feed/278cab38-f438-459f-bae1-8cb4f6dc5436.xml', category: 'Musique',     statut: 'comptabilisé' },
  { id: 'e1-63', name: 'Drôle d\'endroit pour une rencontre',             url: 'https://feeds.audiomeans.fr/feed/1f679704-d4ce-4a80-aadb-380f7ed08072.xml', category: 'Divertissement', statut: 'comptabilisé' },
  { id: 'e1-64', name: "L'édito politique d'Alexandre Devecchio",         url: 'https://feeds.audiomeans.fr/feed/a58f57cc-71b0-4e5b-a349-4a8ba3479f80.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-65', name: 'Pop culture',                                     url: 'https://feeds.audiomeans.fr/feed/f2265776-504d-4ff6-89b0-784deacfcb38.xml', category: 'Culture',     statut: 'comptabilisé' },
  { id: 'e1-66', name: 'L\'édito du JDD',                                 url: 'https://feeds.audiomeans.fr/feed/0bfadaff-71b8-43ce-b964-4199e425207e.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-67', name: 'La revue de presse internationale',               url: 'https://feeds.audiomeans.fr/feed/8f59879f-806a-46dd-aa79-9160e503b679.xml', category: 'Info',        statut: 'comptabilisé' },
  { id: 'e1-68', name: "L'histoire dingue",                               url: 'https://feeds.audiomeans.fr/feed/82443457-3b11-434e-99cc-9de8338c8a57.xml', category: 'Histoire',    statut: 'comptabilisé' },
  { id: 'e1-69', name: 'La partition',                                    url: 'https://feeds.audiomeans.fr/feed/283ea31f-bb34-407e-bff1-4d2245824ffe.xml', category: 'Musique',     statut: 'comptabilisé' },
  { id: 'e1-70', name: 'Initiatives en France',                           url: 'https://feeds.audiomeans.fr/feed/474e4787-d49f-4473-ab2d-9aebcf510cfa.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-71', name: "L'interview d'Alexandre Le Mer",                  url: 'https://feeds.audiomeans.fr/feed/502ede2c-7341-4477-a374-e27a0c64d738.xml', category: 'Interviews',  statut: 'comptabilisé' },
  { id: 'e1-72', name: 'Comme un lundi',                                  url: 'https://feeds.audiomeans.fr/feed/db384986-c141-4f27-b4f4-652bc6064c31.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-73', name: 'Le pari gagnant',                                 url: 'https://feeds.audiomeans.fr/feed/361d9d7c-191f-419f-833e-83f498149fed.xml', category: 'Sport',       statut: 'comptabilisé' },
  { id: 'e1-74', name: 'Les pronostics hippiques',                        url: 'https://feeds.audiomeans.fr/feed/03f60f8c-8247-4c78-99dc-faa175730ec3.xml', category: 'Sport',       statut: 'comptabilisé' },
  { id: 'e1-75', name: "L'invite actu",                                   url: 'https://feeds.audiomeans.fr/feed/82faf41f-e3ee-4e5f-80f5-42f177d513e2.xml', category: 'Interviews',  statut: 'comptabilisé' },
  { id: 'e1-76', name: "L'édito de Praud",                                url: 'https://feeds.audiomeans.fr/feed/24076e71-d1f1-4e8f-8c86-3840ee6562ad.xml', category: 'Éditos',      statut: 'comptabilisé' },
  { id: 'e1-77', name: 'Les audiences',                                   url: 'https://feeds.audiomeans.fr/feed/a99c7a56-9ff6-4320-b559-d066c0977f22.xml', category: 'Médias',      statut: 'comptabilisé' },
  { id: 'e1-78', name: 'Le journal des médias',                           url: 'https://feeds.audiomeans.fr/feed/0edf40bd-9b3c-4428-9bfb-230f4bf98895.xml', category: 'Médias',      statut: 'comptabilisé' },
  { id: 'e1-79', name: "Le portrait sonore de l'invité",                  url: 'https://feeds.audiomeans.fr/feed/397935a1-ddef-48a3-9659-caaef04c70a3.xml', category: 'Interviews',  statut: 'comptabilisé' },
  { id: 'e1-80', name: 'Les indispensables',                              url: 'https://feeds.audiomeans.fr/feed/5f798351-a176-416c-abda-8a12d48774fe.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-81', name: "L'invité culture",                                url: 'https://feeds.audiomeans.fr/feed/2b1e500d-8b2f-47e1-8f17-cae751c4b281.xml', category: 'Culture',     statut: 'comptabilisé' },
  { id: 'e1-82', name: "L'invité media",                                  url: 'https://feeds.audiomeans.fr/feed/d083eb0b-49b3-479b-b02a-6895f18a7fab.xml', category: 'Médias',      statut: 'comptabilisé' },
  { id: 'e1-83', name: 'Top à Wall Street',                               url: 'https://feeds.audiomeans.fr/feed/f2303b00-a943-4ab0-8702-aa97447e6112.xml', category: 'Économie',    statut: 'hors-comptage' },
  { id: 'e1-84', name: 'L\'édito de Marie Estelle Dupont',                url: 'https://feeds.audiomeans.fr/feed/301b48c3-3751-46d1-b740-9508bac8be91.xml', category: 'Éditos',      statut: 'hors-comptage' },
  { id: 'e1-85', name: "Les débats d'Europe Soir",                        url: 'https://feeds.audiomeans.fr/feed/c9c019ab-6ec7-49de-a7c2-e6c50ddf2e37.xml', category: 'Émissions',   statut: 'hors-comptage' },
  { id: 'e1-86', name: "L'invité d'Europe 1 Soir",                        url: 'https://feeds.audiomeans.fr/feed/77dd9729-e2b2-462a-90fa-d6b45464ed8e.xml', category: 'Interviews',  statut: 'hors-comptage' },
  { id: 'e1-87', name: 'La pépite',                                       url: 'https://feeds.audiomeans.fr/feed/d8da0358-f829-400a-a9bd-836a08c5cfcb.xml', category: 'Émissions',   statut: 'hors-comptage' },
  { id: 'e1-88', name: 'La belle histoire de la France bouge',            url: 'https://feeds.audiomeans.fr/feed/506f075f-8a18-42bf-b589-a60d7d65fef0.xml', category: 'Émissions',   statut: 'hors-comptage' },
  { id: 'e1-89', name: 'Ai-je le droit ?',                                url: 'https://feeds.audiomeans.fr/feed/5b279160-ca91-477b-99b1-4276074257ac.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-90', name: 'Bienvenue chez vous',                             url: 'https://feeds.audiomeans.fr/feed/aefbab20-4311-449c-8d7e-12b6d1f4b5b4.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-91', name: 'Par ici les sorties',                             url: 'https://feeds.audiomeans.fr/feed/9d4e94a2-0ac1-47bc-b677-3143eb989333.xml', category: 'Culture',     statut: 'comptabilisé' },
  { id: 'e1-92', name: 'Les balades du week-end',                         url: 'https://feeds.audiomeans.fr/feed/c6e434d6-801e-4849-b56e-747d6d5a51ea.xml', category: 'Émissions',   statut: 'comptabilisé' },
  { id: 'e1-93', name: 'Une date, une histoire',                          url: 'https://feeds.audiomeans.fr/feed/39d1fc14-8d85-4bba-afe0-2cf9e3b4053f.xml', category: 'Histoire',    statut: 'comptabilisé' },
  { id: 'e1-94', name: 'Le grand entretien',                              url: 'https://feeds.audiomeans.fr/feed/8670e1d5-b8d8-486b-9ea4-e8d5c09966f5.xml', category: 'Interviews',  statut: 'hors-comptage' },
  { id: 'e1-95', name: 'Les news',                                        url: 'https://feeds.audiomeans.fr/feed/34e71064-2a44-4541-bec3-4c21ddf69bfe.xml', category: 'Info',        statut: 'hors-comptage' },
  { id: 'e1-96', name: 'Le débat de la semaine',                          url: 'https://feeds.audiomeans.fr/feed/0ba247d7-b0e0-4c22-87f5-7c84cfdea897.xml', category: 'Émissions',   statut: 'hors-comptage' },
  { id: 'e1-97', name: "Le débat d'E1 soir week-end",                     url: 'https://feeds.audiomeans.fr/feed/c9c019ab-6ec7-49de-a7c2-e6c50ddf2e37.xml', category: 'Émissions',   statut: 'hors-comptage' },
  { id: 'e1-98', name: "L'interview politique d'E1 soir week-end",        url: 'https://feeds.audiomeans.fr/feed/a32f5059-de31-4db9-8ae9-8ded1af35316.xml', category: 'Interviews',  statut: 'hors-comptage' },
  { id: 'e1-99', name: 'Dans la bibliothèque',                            url: 'https://feeds.audiomeans.fr/feed/c35816b2-174c-4f9e-9889-6fb86fdd8fe5.xml', category: 'Culture',     statut: 'hors-comptage' },
];

// ===== ARTICLES EUROPE 1 (25 rubriques) =====
const ARTICLES_E1 = [
  { id: 'a1-01', name: 'Société',            url: 'https://www.europe1.fr/rss/societe',              category: 'Société',            type: 'article' },
  { id: 'a1-02', name: 'Politique',          url: 'https://www.europe1.fr/rss/politique',            category: 'Politique',          type: 'article' },
  { id: 'a1-03', name: 'Sport',              url: 'https://www.europe1.fr/rss/sport',                category: 'Sport',              type: 'article' },
  { id: 'a1-04', name: 'Culture',            url: 'https://www.europe1.fr/rss/culture',              category: 'Culture',            type: 'article' },
  { id: 'a1-05', name: 'Faits divers',       url: 'https://www.europe1.fr/rss/faits-divers',         category: 'Faits divers',       type: 'article' },
  { id: 'a1-06', name: 'Médias',             url: 'https://www.europe1.fr/rss/medias',               category: 'Médias',             type: 'article' },
  { id: 'a1-07', name: 'Économie',           url: 'https://www.europe1.fr/rss/economie',             category: 'Économie',           type: 'article' },
  { id: 'a1-08', name: 'International',      url: 'https://www.europe1.fr/rss/international',        category: 'International',      type: 'article' },
  { id: 'a1-09', name: 'Santé',              url: 'https://www.europe1.fr/rss/sante',                category: 'Santé',              type: 'article' },
  { id: 'a1-10', name: 'People',             url: 'https://www.europe1.fr/rss/people',               category: 'People',             type: 'article' },
  { id: 'a1-11', name: 'Immobilier',         url: 'https://www.europe1.fr/rss/immobilier',           category: 'Immobilier',         type: 'article' },
  { id: 'a1-12', name: 'Guide shopping',     url: 'https://www.europe1.fr/rss/Guide%20shopping',     category: 'Guide shopping',     type: 'article' },
  { id: 'a1-13', name: 'Police-Justice',     url: 'https://www.europe1.fr/rss/police%20-%20justice', category: 'Police-Justice',     type: 'article' },
  { id: 'a1-14', name: 'Sciences',           url: 'https://www.europe1.fr/rss/sciences',             category: 'Sciences',           type: 'article' },
  { id: 'a1-15', name: 'Environnement',      url: 'https://www.europe1.fr/rss/environnement',        category: 'Environnement',      type: 'article' },
  { id: 'a1-16', name: 'Technologies',       url: 'https://www.europe1.fr/rss/technologies',         category: 'Technologies',       type: 'article' },
  { id: 'a1-17', name: 'Animaux',            url: 'https://www.europe1.fr/rss/animaux',              category: 'Animaux',            type: 'article' },
  { id: 'a1-18', name: 'Cuisine',            url: 'https://www.europe1.fr/rss/cuisine',              category: 'Cuisine',            type: 'article' },
  { id: 'a1-19', name: 'Maison',             url: 'https://www.europe1.fr/rss/maison',               category: 'Maison',             type: 'article' },
  { id: 'a1-20', name: 'Lifestyle',          url: 'https://www.europe1.fr/rss/lifestyle',            category: 'Lifestyle',          type: 'article' },
  { id: 'a1-21', name: 'Insolite',           url: 'https://www.europe1.fr/rss/insolite',             category: 'Insolite',           type: 'article' },
  { id: 'a1-22', name: 'Horoscope',          url: 'https://www.europe1.fr/rss/horoscope',            category: 'Horoscope',          type: 'article' },
  { id: 'a1-23', name: 'Météo',              url: 'https://www.europe1.fr/rss/m%C3%A9t%C3%A9o',     category: 'Météo',              type: 'article' },
  { id: 'a1-24', name: 'Voyage',             url: 'https://www.europe1.fr/rss/voyage',               category: 'Voyage',             type: 'article' },
  { id: 'a1-25', name: 'Vie professionnelle',url: 'https://www.europe1.fr/rss/vie%20professionnelle',category: 'Vie professionnelle', type: 'article' },
];

// All feeds = 99 podcasts + 25 articles = 124 feeds
const ALL_FEEDS = [...PODCASTS_E1, ...ARTICLES_E1];

// Feeds to monitor by default for scheduled alerts (only comptabilisé podcasts)
const DEFAULT_FEEDS = PODCASTS_E1.filter(f => f.statut === 'comptabilisé');

module.exports = { PODCASTS_E1, ARTICLES_E1, ALL_FEEDS, DEFAULT_FEEDS };
